name: Create Release

on:
  push:
    tags:
      - 'v*'  # Se ejecutará cuando se cree un tag con formato "v1.0", "v2.1", etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
